name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get install -y libgles2-mesa-dev
    - uses: actions/checkout@v2
    - name: Build source
      run: cargo build --verbose
    # - name: Run tests
    #   env:
    #     DISPLAY: ":99"
    #   run: |
    #     sudo apt-get install -y libgl1-mesa-glx libgl1-mesa-dev xvfb
    #     xvfb-run -n 99 -s "-screen 0 640x480x24 -pixdepths 24 +extension GLX +render -noreset" cargo test --verbose -- --test-threads=1
    - name: Generate documentation
      run: cargo doc --verbose
